# -*- coding: utf-8 -*-
"""에중세

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thCP-T0zUzeTd1O3291SLX88D29x94xd
"""

from IPython.core.display import HTML

# api (현재 가상의 날씨 데이터)
weather_data = {
    "temperature": 20,  # 온도 (섭씨)
    "uv_index": 5,  # 자외선 지수 (보통)
    "fine_dust": 45,  # 미세먼지 농도 (µg/m³)
    "humidity": 50,  # 습도 (%)
    "precipitation": "rain"  # 현재 날씨 (rain, snow 또는 clear)
}

# 우산 추천 함수
def recommend_umbrella(precipitation):
    if precipitation == 'rain':
        return "비가 오므로 우산을 챙기세요."
    elif precipitation == 'snow':
        return "눈이 오므로 우산을 챙기세요."
    else:
        return "비나 눈이 오지 않으므로 우산이 필요하지 않습니다."

# 복장 추천
def recommend_outfit(temperature):
    if temperature < -10:
        return "아주 두꺼운 패딩, 내복, 목도리, 장갑, 모자와 귀마개를 착용하세요."
    elif -10 <= temperature < -5:
        return "두꺼운 패딩, 긴 코트, 니트, 목도리와 장갑을 착용하세요."
    elif -5 <= temperature < 5:
        return "두꺼운 코트, 니트, 두꺼운 바지와 목도리를 착용하세요."
    elif 5 <= temperature < 10:
        return "재킷, 스웨터와 긴 바지를 착용하세요."
    elif 10 <= temperature < 15:
        return "얇은 코트와 긴팔 셔츠를 착용하세요."
    elif 15 <= temperature < 20:
        return "가벼운 재킷과 긴팔 티셔츠를 착용하세요."
    elif 20 <= temperature < 25:
        return "반팔 티셔츠와 얇은 바지를 착용하세요."
    else:
        return "반팔 티셔츠, 반바지와 통기성이 좋은 옷을 착용하세요."

# 습도에 따른 추천
def recommend_humidity(humidity):
    if humidity > 60:
        return "통기성이 좋은 린넨 또는 면 소재 옷을 추천합니다."
    elif 40 <= humidity <= 60:
        return "계절에 맞는 일반적인 옷을 추천합니다."
    else:
        return "보습제를 사용하고 피부를 보호하세요."

# 미세먼지 농도에 따른 마스크 추천
def recommend_mask(fine_dust):
    if fine_dust >= 151:
        return "마스크를 꼭 착용하세요."
    elif 81 <= fine_dust <= 150:
        return "마스크 착용을 권장합니다."
    else:
        return "특별한 조치는 필요하지 않습니다."

# 자외선 지수에 따른 선크림 추천
def recommend_sunscreen(uv_index):
    if uv_index >= 11:
        return "실내에 머무르며 긴 옷과 선글라스, 선크림을 착용하세요."
    elif 8 <= uv_index < 11:
        return "10시에서 15시 사이 외출을 자제하고, 긴 옷과 선글라스, 선크림을 착용하세요."
    elif 6 <= uv_index < 8:
        return "정오에 그늘에 머무르며 긴 옷과 선글라스, 선크림을 착용하세요."
    elif 3 <= uv_index < 6:
        return "모자와 선글라스, 선크림을 착용하세요."
    else:
        return "별다른 보호는 필요 없으나, 민감한 피부는 선크림을 사용하는 것이 좋습니다."

# 현재 날씨 정보에 따른 추천 문구
umbrella_advice = recommend_umbrella(weather_data["precipitation"])
outfit_advice = recommend_outfit(weather_data["temperature"])
humidity_advice = recommend_humidity(weather_data["humidity"])
mask_advice = recommend_mask(weather_data["fine_dust"])
sunscreen_advice = recommend_sunscreen(weather_data["uv_index"])

# 웹
html_code = f"""
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>날씨 정보</title>
    <style>
        body {{
            background-color: #add8e6;
            font-family: Arial, sans-serif;
            color: #333;
        }}
        .container {{
            width: 80%;
            margin: 20px auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }}
        header {{
            text-align: center;
            padding: 20px 0;
            background-color: #4b0082;
            color: #ffffff;
            border-radius: 10px 10px 0 0;
        }}
        section {{
            margin: 20px 0;
            padding: 20px;
            background-color: #e6f7ff;
            border-radius: 10px;
        }}
        .recommendation p {{ color: #333; }}
        strong {{ color: #ff4500; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>오늘의 날씨 정보</h1>
            <p>온도, 자외선 지수, 미세먼지 농도 등을 실시간으로 확인하세요.</p>
        </header>
        <section>
            <h2>현재 날씨</h2>
            <div>
                <p><strong>온도:</strong> {weather_data["temperature"]}°C</p>
                <p><strong>자외선 지수:</strong> {weather_data["uv_index"]} (보통)</p>
                <p><strong>미세먼지 농도:</strong> {weather_data["fine_dust"]} µg/m³</p>
                <p><strong>습도:</strong> {weather_data["humidity"]}%</p>
                <p><strong>현재 날씨:</strong> {"맑음" if weather_data["precipitation"] == "clear" else "비" if weather_data["precipitation"] == "rain" else "눈"}</p>
            </div>
        </section>
        <section>
            <h2>추천 사항</h2>
            <div class="recommendation">
                <p><strong>우산:</strong> {umbrella_advice}</p>
                <p><strong>복장:</strong> {outfit_advice}</p>
                <p><strong>습도:</strong> {humidity_advice}</p>
                <p><strong>미세먼지 마스크:</strong> {mask_advice}</p>
                <p><strong>선크림:</strong> {sunscreen_advice}</p>
            </div>
        </section>
        <footer>
            <p>© 2024 날씨 정보. All rights reserved.</p>
             <p><a href="https://your-weather-site-link.com" target="_blank" style="color: #ff4500; text-decoration: none;">날씨 사이트 바로가기</a></p>
        </footer>
    </div>
</body>
</html>
"""

# HTML 코드 출력
display(HTML(html_code))